/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package root;

import java.util.ArrayList;

//import static spark.Spark.get;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        /*
        get("/compute",
            (rq,rs) -> {
                Map<String, String> map = new HashMap<String, String>();
                map.put("result","not computed yet!");
                return new ModelAndView(map, "compute.mustache");
                },
                new MustacheTemplateEngine()
        );*/

    }

    public static boolean search(ArrayList <Integer> arr, int e){
        System.out.println("inside search");

        if(arr == null)return false;

        for(int element : arr){
            if(element == e)return true;
        }
        return false;
    }

}
