/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package root;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void classPassed(){
        ArrayList <Integer> arr = new ArrayList<Integer>(Arrays.asList(10,10,5,5,10));
        assertTrue(App.search(arr, 100,100,100));
    }
    @Test
    public void classNotPassed(){
        ArrayList <Integer> arr = new ArrayList<Integer>(Arrays.asList(0,5,10,5,5));
        assertFalse(App.search(arr, 10,20,15));
    }
    @Test
    public void testEmptyArray(){
        ArrayList <Integer> arr = new ArrayList<Integer>();
        assertFalse(App.search(arr, 60,60,60));
    }
    @Test
    public void nullArray(){
        assertFalse(App.search(null, 60,60,60));
    }
}
